os: linux
dist: bionic
group: edge

# services: 
# - mongodb
# before_script:
# - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
# script:
# - sleep 11
# - systemctl status mongodb
# - systemctl status mongod
# - netstat -nltp

# language: erlang
# otp_release:
#   - 18.2.1
# script:
# - date
# - erl -noshell -eval 'io:fwrite("Hello, World!\n"), init:stop().'

addons:
  mariadb: '10.3'
script:
  - ls -la /var/run/mysqld
  - mysql -e 'CREATE DATABASE myapp_test;'
  - sudo mysql -e 'CREATE DATABASE myapp_test2;'
  - mysql -e "SELECT * FROM mysql.user;"
  - sudo ls -la /etc | grep init
